<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Hey Santa!</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/style.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
<div class = "container">
    <div class="wrapper">
        <form  target="_self" method="POST" id="loginForm"  class="form-signin">
            <h3 class="form-signin-heading"Hello</h3>
            <img src="http://zezete2.z.e.pic.centerblog.net/7badf450.png" style=" height: 112px; ">

            <label for="username">
                Login :
                <input type="text" class="form-control" name="username" placeholder="Username" required="" autofocus="" />
            </label>
            <label for="password">
                Password :
                <input type="password" class="form-control" name="password" placeholder="Password" required=""/>
            </label>

            <button class="btn btn-lg btn-primary btn-block"  name="Submit" value="Login" type="Submit">Login</button><br>
            <button type="submit" class="btn btn-default col-md-12"><a href="room">create room</a></button>
        </form>
    </div>
</body>
</html>
