<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Hey Santa!</title>
</head>
<body>
<h1>Hello</h1>
<ul>
    <li><a href="room">create room</a></li>
</ul>
<form target="_self" method="POST" id="loginForm">
    <label for="username">
        Login :
        <input name="username" type="text" value=""/>
    </label>
    <label for="password">
        Password :
        <input name="password" type="password" value=""/>
    </label>
    <input type="submit">
</form>
</body>
</html>
